# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
 branches:
   include:
     - Developer

variables:
  Parameters.solution: '**/Website/SourceCode/Profiles/Profiles.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Parameters.Artifactname: 'ProfilesRNS_Drop'
  Parameters.Contents: '/**/Profiles.zip'
  Parameters.packagetype: '*.zip'
  Parameters.Websitename: 'w3.umassmed.edu'
  Parameters.VirtualApplication: 'Profiles'
  Parameters.msbuildArgs: '/t:rebuild /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)\build"'



stages:
- stage: Build_Application
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
      # vmImage requires update per pipeline
      demands:
      - msbuild
      - visualstudio
      - vstest
    steps:
    - task: NuGetToolInstaller@0
      displayName: Use NuGet 4.4.1
      inputs:
        versionSpec: 4.4.1

    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        command: 'restore'
        restoreSolution: '$(Parameters.solution)'
        feedsToUse: 'config'
    - task: VSBuild@1
      displayName: Build solution
      inputs:
        solution: $(Parameters.solution)
        platform: $(BuildPlatform)
        configuration: $(BuildConfiguration)
        msbuildArgs: $(Parameters.msbuildArgs)

    #- task: CopyFiles@2
    #  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/build'
    #  inputs:
    #    SourceFolder: $(Build.Repository.LocalPath)
    #    TargetFolder: $(Build.ArtifactStagingDirectory)/build
    #    Contents: $(Parameters.Contents)
    #    flattenFolders: true
        
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)/build/Profiles.zip
        ArtifactName: $(Parameters.ArtifactName)
      condition: succeededOrFailed()

- stage: Development  
  jobs:
    - deployment: DeployEmployeeGiving_Dev
      displayName: DeployEmployeeGiving_Dev
      #pool:                # see pool schema
        #name: SSP Deploy
        #demands: 
      #dependsOn: Build
      #condition: succeeded('Build')
      continueOnError: true                # 'true' if future jobs should run even if this job fails; defaults to 'false'
      # container: containerReference # container to run the job inside
      #services: { string: string | container } # container resources to run as a service container
      timeoutInMinutes: 10        # how long to run the job before automatically cancelling
      #cancelTimeoutInMinutes: nonEmptyString  # how much time to give 'run always even if cancelled tasks' before killing them
      variables:
        Comecc: 'data source=DEVAGLISTENER;Initial Catalog=Comecc;Integrated Security=true;MultipleActiveResultSets=True;App=EntityFramework'

      environment: 
        name: Development
        resourceType: VirtualMachine
        tags: saintbernard_dev 
        # Tags needs to be updated per Pipeline
      strategy: 
        runOnce:
          deploy:
            steps:

             - task: IISWebAppManagementOnMachineGroup@0
               displayName: 'IIS Vir App config'
               inputs:
                IISDeploymentType: 'IISWebApplication'
                ParentWebsiteNameForApplication: 'dev-w3.umassmed.edu'
                VirtualPathForApplication: '/EmployeeGiving'
                PhysicalPathForApplication: 'D:\WebContent\dev-w3.umassmed.edu\EmployeeGiving'

             - task: IISWebAppDeploymentOnMachineGroup@0
               displayName: 'IIS Web App Deploy'
               inputs:
                WebSiteName: 'dev-$(Parameters.Websitename)'
                VirtualApplication: $(Parameters.VirtualApplication)
                Package: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)/$(Parameters.packagetype)'
                #XmlTransformation: true
                RemoveAdditionalFilesFlag: true
                #AdditionalArguments: '-transform **\*.$(Release.EnvironmentName).config -xml **\*.config'
                XmlVariableSubstitution: true

             #- task: FileTransform@1
              # inputs:
                #folderPath: 'D:\WebContent\dev-w3.umassmed.edu\EmployeeGiving'
                #FolderPath is pipeline specific
                #enableXmlTransform: true
                #xmlTransformationRules: '-transform web.Development.config -xml web.config'
             - task: DeleteFiles@1
               inputs:
                SourceFolder: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)'
                Contents: $(Parameters.packagetype)

